[package]
name = "vrpn-base"
version = "0.1.0"
authors = ["Ryan Pavlik <ryan.pavlik@collabora.com>"]
license = "BSL-1.0"

[dependencies]
bytes = "^0.4.10"
bitmask = "^0.4.0"
quick-error = "^1.2.2"
libc = "^0.2"
itertools = "^0.7"
